In [72]:
from sklearn.datasets import load_wine
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier

In [73]:
wine = load_wine()
X = wine.data
y = wine.target

In [74]:
clf = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [75]:
feature_selection = RFE(clf, n_features_to_select=5, step=1)

In [76]:
fs = feature_selection.fit(X, y)

In [77]:
fs.support_

array([False, False, False, False, False, False,  True, False, False,
        True,  True,  True,  True])

In [78]:
fs.ranking_

array([8, 7, 9, 6, 3, 5, 1, 4, 2, 1, 1, 1, 1])

In [58]:
from sklearn.datasets import load_wine
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

In [59]:
wine = load_wine()
X = wine.data
y = wine.target

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [66]:
clf = DecisionTreeClassifier(max_leaf_nodes=1, random_state=0)

In [67]:
feature_selection = RFE(clf, n_features_to_select=5, step=1)

In [68]:
fs = feature_selection.fit(X, y)

In [69]:
fs.support_

array([ True, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True])

In [70]:
fs.ranking_

array([1, 5, 9, 8, 6, 7, 1, 4, 3, 2, 1, 1, 1])

In [79]:
for i in range(X.shape[1]):
	print('Column: %d, Selected %s, Rank: %.3f' % (i, fs.support_[i], fs.ranking_[i]))

Column: 0, Selected False, Rank: 8.000
Column: 1, Selected False, Rank: 7.000
Column: 2, Selected False, Rank: 9.000
Column: 3, Selected False, Rank: 6.000
Column: 4, Selected False, Rank: 3.000
Column: 5, Selected False, Rank: 5.000
Column: 6, Selected True, Rank: 1.000
Column: 7, Selected False, Rank: 4.000
Column: 8, Selected False, Rank: 2.000
Column: 9, Selected True, Rank: 1.000
Column: 10, Selected True, Rank: 1.000
Column: 11, Selected True, Rank: 1.000
Column: 12, Selected True, Rank: 1.000


In [80]:
from numpy import mean
from numpy import std
from sklearn.datasets import load_wine
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
# define dataset
wine = load_wine()
X = wine.data
y = wine.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
# create pipeline
clf = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
feature_selection = RFE(clf, n_features_to_select=5, step=1)
fs = feature_selection.fit(X, y)
pipeline = Pipeline(steps=[('s',fs),('m',clf)])
# evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.893 (0.077)
